on: push
jobs: 
  first-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: microsoft/setup-msbuild@v2
      - run: dotnet restore 
      - run: dotnet build
      - run: dotnet test
