on: [push, workflow_dispatch]
jobs: 
 job:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull coherentsolutions/rest-training:2.0 
      - run: docker run -d -p 49000:8082 coherentsolutions/rest-training:2.0   
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore 
      - run: dotnet build 
      - run: dotnet test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ${{ env.WORKING_DIR }}/bin/Debug/net8.0/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history


      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
