name: Demo
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Run tests
        run: npm run test
